##\
# This file is a part of the phpMussel package.
# Homepage: https://phpmussel.github.io/
#
# PHPMUSSEL COPYRIGHT 2013 AND BEYOND BY THE PHPMUSSEL TEAM.
#
# License: GNU/GPLv2
# @see LICENSE.txt
#
# This file: Configuration defaults file (last modified: 2021.05.07).
##/

Config Defaults:
 general:
  cleanup:
   type: "bool"
   default: true
  scan_log:
   type: "string"
   default: "scan_log.txt"
  scan_log_serialized:
   type: "string"
   default: "scan_log_serialized.txt"
  scan_kills:
   type: "string"
   default: "scan_kills.txt"
  error_log:
   type: "string"
   default: ""
  truncate:
   type: "kb"
   default: "0KB"
   preview: "kb"
  log_rotation_limit:
   type: "int"
   default: 0
  log_rotation_action:
   type: "string"
   default: "Delete"
   choices:
    Delete: "Delete"
    Archive: "Archive"
  timezone:
   type: "timezone"
   default: "SYSTEM"
  timeOffset:
   type: "int"
   default: 0
   preview: "minutes"
  timeFormat:
   type: "string"
   default: "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}"
   preview: "allow_other"
   allow_other: true
   choices:
    "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}": "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}"
    "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss}": "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss}"
    "{Day}, {dd} {Mon} {yyyy}": "{Day}, {dd} {Mon} {yyyy}"
    "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}"
    "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss}": "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss}"
    "{yyyy}.{mm}.{dd}": "{yyyy}.{mm}.{dd}"
    "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}"
    "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss}": "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss}"
    "{yyyy}-{mm}-{dd}": "{yyyy}-{mm}-{dd}"
    "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}"
    "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss}": "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss}"
    "{yyyy}/{mm}/{dd}": "{yyyy}/{mm}/{dd}"
    "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss} {tz}"
    "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss}": "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss}"
    "{dd}.{mm}.{yyyy}": "{dd}.{mm}.{yyyy}"
    "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss} {tz}"
    "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss}": "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss}"
    "{dd}-{mm}-{yyyy}": "{dd}-{mm}-{yyyy}"
    "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss} {tz}"
    "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss}": "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss}"
    "{dd}/{mm}/{yyyy}": "{dd}/{mm}/{yyyy}"
    "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss} {tz}"
    "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss}": "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss}"
    "{mm}.{dd}.{yyyy}": "{mm}.{dd}.{yyyy}"
    "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss} {tz}"
    "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss}": "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss}"
    "{mm}-{dd}-{yyyy}": "{mm}-{dd}-{yyyy}"
    "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss} {tz}"
    "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss}": "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss}"
    "{mm}/{dd}/{yyyy}": "{mm}/{dd}/{yyyy}"
    "{yy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}": "{yy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}"
    "{yy}.{mm}.{dd} {hh}:{ii}:{ss}": "{yy}.{mm}.{dd} {hh}:{ii}:{ss}"
    "{yy}.{mm}.{dd}": "{yy}.{mm}.{dd}"
    "{yy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}": "{yy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}"
    "{yy}-{mm}-{dd} {hh}:{ii}:{ss}": "{yy}-{mm}-{dd} {hh}:{ii}:{ss}"
    "{yy}-{mm}-{dd}": "{yy}-{mm}-{dd}"
    "{yy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}": "{yy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}"
    "{yy}/{mm}/{dd} {hh}:{ii}:{ss}": "{yy}/{mm}/{dd} {hh}:{ii}:{ss}"
    "{yy}/{mm}/{dd}": "{yy}/{mm}/{dd}"
    "{dd}.{mm}.{yy} {hh}:{ii}:{ss} {tz}": "{dd}.{mm}.{yy} {hh}:{ii}:{ss} {tz}"
    "{dd}.{mm}.{yy} {hh}:{ii}:{ss}": "{dd}.{mm}.{yy} {hh}:{ii}:{ss}"
    "{dd}.{mm}.{yy}": "{dd}.{mm}.{yy}"
    "{dd}-{mm}-{yy} {hh}:{ii}:{ss} {tz}": "{dd}-{mm}-{yy} {hh}:{ii}:{ss} {tz}"
    "{dd}-{mm}-{yy} {hh}:{ii}:{ss}": "{dd}-{mm}-{yy} {hh}:{ii}:{ss}"
    "{dd}-{mm}-{yy}": "{dd}-{mm}-{yy}"
    "{dd}/{mm}/{yy} {hh}:{ii}:{ss} {tz}": "{dd}/{mm}/{yy} {hh}:{ii}:{ss} {tz}"
    "{dd}/{mm}/{yy} {hh}:{ii}:{ss}": "{dd}/{mm}/{yy} {hh}:{ii}:{ss}"
    "{dd}/{mm}/{yy}": "{dd}/{mm}/{yy}"
    "{mm}.{dd}.{yy} {hh}:{ii}:{ss} {tz}": "{mm}.{dd}.{yy} {hh}:{ii}:{ss} {tz}"
    "{mm}.{dd}.{yy} {hh}:{ii}:{ss}": "{mm}.{dd}.{yy} {hh}:{ii}:{ss}"
    "{mm}.{dd}.{yy}": "{mm}.{dd}.{yy}"
    "{mm}-{dd}-{yy} {hh}:{ii}:{ss} {tz}": "{mm}-{dd}-{yy} {hh}:{ii}:{ss} {tz}"
    "{mm}-{dd}-{yy} {hh}:{ii}:{ss}": "{mm}-{dd}-{yy} {hh}:{ii}:{ss}"
    "{mm}-{dd}-{yy}": "{mm}-{dd}-{yy}"
    "{mm}/{dd}/{yy} {hh}:{ii}:{ss} {tz}": "{mm}/{dd}/{yy} {hh}:{ii}:{ss} {tz}"
    "{mm}/{dd}/{yy} {hh}:{ii}:{ss}": "{mm}/{dd}/{yy} {hh}:{ii}:{ss}"
    "{mm}/{dd}/{yy}": "{mm}/{dd}/{yy}"
    "{yyyy}å¹´{m}æœˆ{d}æ—¥ {hh}æ™‚{ii}åˆ†{ss}ç§’": "{yyyy}å¹´{m}æœˆ{d}æ—¥ {hh}æ™‚{ii}åˆ†{ss}ç§’"
    "{yyyy}å¹´{m}æœˆ{d}æ—¥ {hh}:{ii}:{ss} {tz}": "{yyyy}å¹´{m}æœˆ{d}æ—¥ {hh}:{ii}:{ss} {tz}"
    "{yyyy}å¹´{m}æœˆ{d}æ—¥": "{yyyy}å¹´{m}æœˆ{d}æ—¥"
    "{yy}å¹´{m}æœˆ{d}æ—¥ {hh}æ™‚{ii}åˆ†{ss}ç§’": "{yy}å¹´{m}æœˆ{d}æ—¥ {hh}æ™‚{ii}åˆ†{ss}ç§’"
    "{yy}å¹´{m}æœˆ{d}æ—¥ {hh}:{ii}:{ss} {tz}": "{yy}å¹´{m}æœˆ{d}æ—¥ {hh}:{ii}:{ss} {tz}"
    "{yy}å¹´{m}æœˆ{d}æ—¥": "{yy}å¹´{m}æœˆ{d}æ—¥"
    "{yyyy}ë…„ {m}ì›” {d}ì¼ {hh}ì‹œ {ii}ë¶„ {ss}ì´ˆ": "{yyyy}ë…„ {m}ì›” {d}ì¼ {hh}ì‹œ {ii}ë¶„ {ss}ì´ˆ"
    "{yyyy}ë…„ {m}ì›” {d}ì¼ {hh}:{ii}:{ss} {tz}": "{yyyy}ë…„ {m}ì›” {d}ì¼ {hh}:{ii}:{ss} {tz}"
    "{yyyy}ë…„ {m}ì›” {d}ì¼": "{yyyy}ë…„ {m}ì›” {d}ì¼"
    "{yy}ë…„ {m}ì›” {d}ì¼ {hh}ì‹œ {ii}ë¶„ {ss}ì´ˆ": "{yy}ë…„ {m}ì›” {d}ì¼ {hh}ì‹œ {ii}ë¶„ {ss}ì´ˆ"
    "{yy}ë…„ {m}ì›” {d}ì¼ {hh}:{ii}:{ss} {tz}": "{yy}ë…„ {m}ì›” {d}ì¼ {hh}:{ii}:{ss} {tz}"
    "{yy}ë…„ {m}ì›” {d}ì¼": "{yy}ë…„ {m}ì›” {d}ì¼"
    "{yyyy}-{mm}-{dd}T{hh}:{ii}:{ss}{t:z}": "{yyyy}-{mm}-{dd}T{hh}:{ii}:{ss}{t:z}"
    "{d}. {m}. {yyyy}": "{d}. {m}. {yyyy}"
  ipaddr:
   type: "string"
   default: "REMOTE_ADDR"
   preview: "allow_other"
   allow_other: true
   choices:
    HTTP_INCAP_CLIENT_IP: "HTTP_INCAP_CLIENT_IP (Incapsula)"
    HTTP_CF_CONNECTING_IP: "HTTP_CF_CONNECTING_IP (Cloudflare)"
    CF-Connecting-IP: "CF-Connecting-IP (Cloudflare)"
    HTTP_X_FORWARDED_FOR: "HTTP_X_FORWARDED_FOR (Cloudbric)"
    X-Forwarded-For: "X-Forwarded-For (Squid)"
    REMOTE_ADDR: "REMOTE_ADDR ({label_default})"
   See also:
    NGINX Reverse Proxy: "https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/"
    Squid configuration directive forwarded_for: "http://www.squid-cache.org/Doc/config/forwarded_for/"
  enable_plugins:
   type: "bool"
   default: true
  forbid_on_block:
   type: "bool"
   default: true
  delete_on_sight:
   type: "bool"
   default: false
  lang:
   type: "string"
   default: "en"
   choices:
    en: "English"
    ar: "Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©"
    bn: "à¦¬à¦¾à¦‚à¦²à¦¾"
    de: "Deutsch"
    es: "EspaÃ±ol"
    fr: "FranÃ§ais"
    hi: "à¤¹à¤¿à¤‚à¤¦à¥€"
    id: "Bahasa Indonesia"
    it: "Italiano"
    ja: "æ—¥æœ¬èªž"
    ko: "í•œêµ­ì–´"
    nl: "Nederlandse"
    pt: "PortuguÃªs"
    ru: "Ð ÑƒÑÑÐºÐ¸Ð¹"
    th: "à¸ à¸²à¸©à¸²à¹„à¸—à¸¢"
    tr: "TÃ¼rkÃ§e"
    ur: "Ø§Ø±Ø¯Ùˆ"
    vi: "Tiáº¿ng Viá»‡t"
    zh: "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
    zh-tw: "ä¸­æ–‡ï¼ˆå‚³çµ±ï¼‰"
   choice_filter: "FilterLang"
  lang_override:
   type: "bool"
   default: true
  numbers:
   type: "string"
   default: "Latin-1"
   choices:
    Arabic-1: "Ù¡Ù¢Ù£Ù¤Ù¥Ù¦Ù§Ù«Ù¨Ù©"
    Arabic-2: "Ù¡Ù¬Ù¢Ù£Ù¤Ù¬Ù¥Ù¦Ù§Ù«Ù¨Ù©"
    Arabic-3: "Û±Ù¬Û²Û³Û´Ù¬ÛµÛ¶Û·Ù«Û¸Û¹"
    Arabic-4: "Û±Û²Ù¬Û³Û´Ù¬ÛµÛ¶Û·Ù«Û¸Û¹"
    Armenian: "ÕŒÌ…Õ„Ì…Ô¼Ì…ÕÕ‡Ô¿Ô·"
    Base-12: "4b6547.a8"
    Base-16: "12d687.e3"
    Bengali-1: "à§§à§¨,à§©à§ª,à§«à§¬à§­.à§®à§¯"
    Burmese-1: "áá‚áƒá„á…á†á‡.áˆá‰"
    China-1: "123,4567.89"
    Chinese-Simplified: "ä¸€ç™¾äºŒåä¸‰ä¸‡å››åƒäº”ç™¾å…­åä¸ƒç‚¹å…«ä¹"
    Chinese-Simplified-Financial: "å£¹ä½°è´°æ‹¾åè¬è‚†ä»Ÿä¼ä½°é™†æ‹¾æŸ’ç‚¹æŒçŽ–"
    Chinese-Traditional: "ä¸€ç™¾äºŒåä¸‰è¬å››åƒäº”ç™¾å…­åä¸ƒé»žå…«ä¹"
    Chinese-Traditional-Financial: "å£¹ä½°è²³æ‹¾å„è¬è‚†ä»Ÿä¼ä½°é™¸æ‹¾æŸ’é»žæŒçŽ–"
    Fullwidth: "ï¼‘ï¼’ï¼“ï¼”ï¼•ï¼–ï¼—.ï¼˜ï¼™"
    Hebrew: "××³×³×‘×³×§×’×³×™×“×³×š×¡×–"
    India-1: "12,34,567.89"
    India-2: "à¥§à¥¨,à¥©à¥ª,à¥«à¥¬à¥­.à¥®à¥¯"
    India-3: "à«§à«¨,à«©à«ª,à««à«¬à«­.à«®à«¯"
    India-4: "à©§à©¨,à©©à©ª,à©«à©¬à©­.à©®à©¯"
    India-5: "à³§à³¨,à³©à³ª,à³«à³¬à³­.à³®à³¯"
    India-6: "à±§à±¨,à±©à±ª,à±«à±¬à±­.à±®à±¯"
    Japanese: "ç™¾ä¸‡äºŒåä¸‡ä¸‰ä¸‡å››åƒäº”ç™¾å…­åä¸ƒãƒ»å…«ä¹åˆ†"
    Javanese: "ê§‘ê§’ê§“ê§”ê§•ê§–ê§—.ê§˜ê§™"
    Khmer-1: "áŸ¡.áŸ¢áŸ£áŸ¤.áŸ¥áŸ¦áŸ§,áŸ¨áŸ©"
    Lao-1: "à»‘à»’à»“à»”à»•à»–à»—.à»˜à»™"
    Latin-1: "1,234,567.89"
    Latin-2: "1â€¯234â€¯567.89"
    Latin-3: "1.234.567,89"
    Latin-4: "1â€¯234â€¯567,89"
    Latin-5: "1,234,567Â·89"
    Mayan: "ð‹§ð‹®ð‹¦ð‹¨ð‹§.ð‹±ð‹°"
    Mongolian: "á ‘á ’á “á ”á •á –á —.á ˜á ™"
    NoSep-1: "1234567.89"
    NoSep-2: "1234567,89"
    Odia: "à­§à­¨à­©à­ªà­«à­¬à­­.à­®à­¯"
    Roman: "MÌ…CÌ…CÌ…XÌ…XÌ…XÌ…IÌ…VÌ…DLXVII"
    SDN-Dwiggins: "4E6,547;X8"
    SDN-Pitman: "4â†‹6,547;â†Š8"
    Tamil: "à¯²à¯²à¯¨à¯±à¯²à¯©à¯°à¯²à¯ªà¯²à¯«à¯±à¯¬à¯°à¯­"
    Thai-1: "à¹‘,à¹’à¹“à¹”,à¹•à¹–à¹—.à¹˜à¹™"
    Thai-2: "à¹‘à¹’à¹“à¹”à¹•à¹–à¹—.à¹˜à¹™"
    Tibetan: "à¼¡à¼¢à¼£à¼¤à¼¥à¼¦à¼§.à¼¨à¼©"
  quarantine_key:
   type: "string"
   default: ""
  quarantine_max_filesize:
   type: "kb"
   step: "any"
   default: "2MB"
   preview: "kb"
  quarantine_max_usage:
   type: "kb"
   step: "any"
   default: "64MB"
   preview: "kb"
  quarantine_max_files:
   type: "int"
   default: 100
  honeypot_mode:
   type: "bool"
   default: false
  scan_cache_expiry:
   type: "int"
   default: 21600
   preview: "seconds"
  disable_cli:
   type: "bool"
   default: false
  disable_frontend:
   type: "bool"
   default: true
  max_login_attempts:
   type: "int"
   default: 5
  FrontEndLog:
   type: "string"
   default: ""
  disable_webfonts:
   type: "bool"
   default: true
  maintenance_mode:
   type: "bool"
   default: false
  default_algo:
   type: "string"
   default: "PASSWORD_DEFAULT"
   choices:
    PASSWORD_DEFAULT: "PASSWORD_DEFAULT"
    PASSWORD_BCRYPT: "PASSWORD_BCRYPT"
    PASSWORD_ARGON2I: "PASSWORD_ARGON2I (PHP >= 7.2.0)"
    PASSWORD_ARGON2ID: "PASSWORD_ARGON2ID (PHP >= 7.3.0)"
   choice_filter: "FilterByDefined"
  statistics:
   type: "bool"
   default: false
  disabled_channels:
   type: "checkbox"
   default: "VirusTotal_HTTP"
   choices:
    GitHub: "GitHub"
    BitBucket: "BitBucket"
    VirusTotal_HTTPS: "VirusTotal (HTTPS)"
    VirusTotal_HTTP: "VirusTotal (HTTP)"
   value_preg_filter:
    "~\s~": ""
 signatures:
  Active:
   type: "string"
   default: ""
   value_preg_filter:
    "~\s~": ""
  fail_silently:
   type: "bool"
   default: true
  fail_extensions_silently:
   type: "bool"
   default: true
  detect_adware:
   type: "bool"
   default: true
  detect_joke_hoax:
   type: "bool"
   default: true
  detect_pua_pup:
   type: "bool"
   default: true
  detect_packer_packed:
   type: "bool"
   default: true
  detect_shell:
   type: "bool"
   default: true
  detect_deface:
   type: "bool"
   default: true
  detect_encryption:
   type: "bool"
   default: true
 files:
  max_uploads:
   type: "int"
   default: 10
  filesize_limit:
   type: "kb"
   step: "any"
   default: "64MB"
   preview: "kb"
  filesize_response:
   type: "bool"
   default: true
  filetype_whitelist:
   type: "string"
   default: ""
   value_preg_filter:
    "~\s~": ""
  filetype_blacklist:
   type: "string"
   default: "386,acc*,acm,act*,apk,app,ash*,asm*,asx*,ax,bat,bin,ccc,cgi,cmd,com*,cpl,cpp,csh,dll,drv,elf,exe,fxp,gad*,hta*,htp*,ico,inf,ins,inx,ipa,isu,job,js,jse,ksh,lnk,msc,msi,msp,mst,net,ocx,ops,org,osx,out,paf,php*,pif,pl,prg,ps1,reg,rgs,rs,run,scr*,sct,shb,shs,sql*,sys,u3p,url,vb,vbe,vbs*,wor*,ws,wsf,xsl"
   value_preg_filter:
    "~\s~": ""
  filetype_greylist:
   type: "string"
   default: ""
   value_preg_filter:
    "~\s~": ""
  check_archives:
   type: "bool"
   default: true
  filesize_archives:
   type: "bool"
   default: true
  filetype_archives:
   type: "bool"
   default: false
  max_recursion:
   type: "int"
   default: 3
  block_encrypted_archives:
   type: "bool"
   default: true
  max_files_in_archives:
   type: "int"
   default: 0
 attack_specific:
  chameleon_from_php:
   type: "bool"
   default: true
  can_contain_php_file_extensions:
   type: "string"
   default: "inc,md,phar,php*,pzp,sig,tpl,txt,tzt"
   value_preg_filter:
    "~\s~": ""
  chameleon_from_exe:
   type: "bool"
   default: true
  chameleon_to_archive:
   type: "bool"
   default: true
  chameleon_to_doc:
   type: "bool"
   default: true
  chameleon_to_img:
   type: "bool"
   default: true
  chameleon_to_pdf:
   type: "bool"
   default: true
  archive_file_extensions:
   type: "string"
   default: "7z,a,ace,alz,apk,app,ar,arc,arj,ba,bh,bz,bz2,dmg,gz,ice,iso,lha,lz,lzh,lzo,lzw,lzx,mar,pak,pck,pea,phar,rar,rz,s7z,sea,sen,sfx,shar,sqx,tar,tgz,tlz,xar,xp3,xz,yz1,z,zz,paq*,sit*,tbz*,zip*"
   value_preg_filter:
    "~\s~": ""
  block_control_characters:
   type: "bool"
   default: false
  corrupted_exe:
   type: "bool"
   default: true
  decode_threshold:
   type: "kb"
   step: "any"
   default: "512KB"
   preview: "kb"
  scannable_threshold:
   type: "kb"
   step: "any"
   default: "32MB"
   preview: "kb"
  allow_leading_trailing_dots:
   type: "bool"
   default: false
  block_macros:
   type: "bool"
   default: false
   experimental: true
 compatibility:
  ignore_upload_errors:
   type: "bool"
   default: false
  only_allow_images:
   type: "bool"
   default: false
 heuristic:
  threshold:
   type: "int"
   default: 3
 virustotal:
  vt_public_api_key:
   type: "string"
   default: ""
   See also:
    Terms of Service: "https://www.virustotal.com/en/about/terms-of-service/"
    Getting started: "https://developers.virustotal.com/reference"
  vt_suspicion_level:
   type: "int"
   default: 1
  vt_weighting:
   type: "int"
   default: 0
  vt_quota_rate:
   type: "int"
   default: 4
  vt_quota_time:
   type: "int"
   default: 1
   preview: "minutes"
 urlscanner:
  google_api_key:
   type: "string"
   default: ""
   See also:
    Google API Console: "https://console.developers.google.com/"
  maximum_api_lookups:
   type: "int"
   default: 10
  maximum_api_lookups_response:
   type: "bool"
   default: false
  cache_time:
   type: "int"
   default: 3600
   preview: "seconds"
 legal:
  pseudonymise_ip_addresses:
   type: "bool"
   default: true
  privacy_policy:
   type: "url"
   default: ""
   autocomplete: "url"
 template_data:
  theme:
   type: "string"
   default: "default"
   preview: "allow_other"
   allow_other: true
   choices:
    default: "Default"
    bluemetal: "Blue Metal"
    fullmoon: "Full Moon"
    moss: "Moss"
    primer: "Primer"
    primerdark: "Primer Dark"
    rbi: "Red-Blue Inverted"
    slate: "Slate"
   choice_filter: "FilterTheme"
  Magnification:
   type: "float"
   step: "any"
   default: 1
  css_url:
   type: "url"
   default: ""
   autocomplete: "url"
 PHPMailer:
  EventLog:
   type: "string"
   default: ""
  SkipAuthProcess:
   type: "bool"
   default: false
  Enable2FA:
   type: "bool"
   default: false
  Host:
   type: "string"
   default: ""
  Port:
   type: "int"
   default: 587
  SMTPSecure:
   type: "string"
   default: "default"
   choices:
    default: "-"
    tls: "TLS"
    ssl: "SSL"
  SMTPAuth:
   type: "bool"
   default: true
  Username:
   type: "string"
   default: ""
   autocomplete: "username"
  Password:
   type: "string"
   default: ""
   autocomplete: "current-password"
  setFromAddress:
   type: "email"
   default: ""
   autocomplete: "email"
  setFromName:
   type: "string"
   default: ""
   autocomplete: "name"
  addReplyToAddress:
   type: "email"
   default: ""
   autocomplete: "email"
  addReplyToName:
   type: "string"
   default: ""
   autocomplete: "name"
 supplementary_cache_options:
  enable_apcu:
   type: "bool"
   default: false
  enable_memcached:
   type: "bool"
   default: false
  enable_redis:
   type: "bool"
   default: false
  enable_pdo:
   type: "bool"
   default: false
  memcached_host:
   type: "string"
   default: "localhost"
  memcached_port:
   type: "int"
   default: 11211
  redis_host:
   type: "string"
   default: "localhost"
  redis_port:
   type: "int"
   default: 6379
  redis_timeout:
   type: "float"
   step: "any"
   default: 2.5
  pdo_dsn:
   type: "string"
   default: "mysql:dbname=phpmussel;host=localhost;port=3306"
  pdo_username:
   type: "string"
   default: ""
   autocomplete: "username"
  pdo_password:
   type: "string"
   default: ""
   autocomplete: "current-password"
