Config Defaults:
 general:
  cleanup:
   type: bool
   default: true
  scan_log:
   type: string
   default: "scan_log.txt"
  scan_log_serialized:
   type: string
   default: "scan_log_serialized.txt"
  scan_kills:
   type: string
   default: "scan_kills.txt"
  truncate:
   type: kb
   default: "0KB"
   preview: kb
  timezone:
   type: timezone
   default: "SYSTEM"
  timeOffset:
   type: int
   default: 0
   preview: minutes
  timeFormat:
   type: string
   default: "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}"
   choices:
    "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}": "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}"
    "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss}": "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss}"
    "{Day}, {dd} {Mon} {yyyy}": "{Day}, {dd} {Mon} {yyyy}"
    "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}"
    "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss}": "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss}"
    "{yyyy}.{mm}.{dd}": "{yyyy}.{mm}.{dd}"
    "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}"
    "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss}": "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss}"
    "{yyyy}-{mm}-{dd}": "{yyyy}-{mm}-{dd}"
    "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}"
    "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss}": "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss}"
    "{yyyy}/{mm}/{dd}": "{yyyy}/{mm}/{dd}"
    "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss} {tz}"
    "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss}": "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss}"
    "{dd}.{mm}.{yyyy}": "{dd}.{mm}.{yyyy}"
    "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss} {tz}"
    "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss}": "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss}"
    "{dd}-{mm}-{yyyy}": "{dd}-{mm}-{yyyy}"
    "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss} {tz}"
    "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss}": "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss}"
    "{dd}/{mm}/{yyyy}": "{dd}/{mm}/{yyyy}"
    "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss} {tz}"
    "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss}": "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss}"
    "{mm}.{dd}.{yyyy}": "{mm}.{dd}.{yyyy}"
    "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss} {tz}"
    "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss}": "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss}"
    "{mm}-{dd}-{yyyy}": "{mm}-{dd}-{yyyy}"
    "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss} {tz}"
    "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss}": "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss}"
    "{mm}/{dd}/{yyyy}": "{mm}/{dd}/{yyyy}"
    "{yy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}": "{yy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}"
    "{yy}.{mm}.{dd} {hh}:{ii}:{ss}": "{yy}.{mm}.{dd} {hh}:{ii}:{ss}"
    "{yy}.{mm}.{dd}": "{yy}.{mm}.{dd}"
    "{yy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}": "{yy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}"
    "{yy}-{mm}-{dd} {hh}:{ii}:{ss}": "{yy}-{mm}-{dd} {hh}:{ii}:{ss}"
    "{yy}-{mm}-{dd}": "{yy}-{mm}-{dd}"
    "{yy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}": "{yy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}"
    "{yy}/{mm}/{dd} {hh}:{ii}:{ss}": "{yy}/{mm}/{dd} {hh}:{ii}:{ss}"
    "{yy}/{mm}/{dd}": "{yy}/{mm}/{dd}"
    "{dd}.{mm}.{yy} {hh}:{ii}:{ss} {tz}": "{dd}.{mm}.{yy} {hh}:{ii}:{ss} {tz}"
    "{dd}.{mm}.{yy} {hh}:{ii}:{ss}": "{dd}.{mm}.{yy} {hh}:{ii}:{ss}"
    "{dd}.{mm}.{yy}": "{dd}.{mm}.{yy}"
    "{dd}-{mm}-{yy} {hh}:{ii}:{ss} {tz}": "{dd}-{mm}-{yy} {hh}:{ii}:{ss} {tz}"
    "{dd}-{mm}-{yy} {hh}:{ii}:{ss}": "{dd}-{mm}-{yy} {hh}:{ii}:{ss}"
    "{dd}-{mm}-{yy}": "{dd}-{mm}-{yy}"
    "{dd}/{mm}/{yy} {hh}:{ii}:{ss} {tz}": "{dd}/{mm}/{yy} {hh}:{ii}:{ss} {tz}"
    "{dd}/{mm}/{yy} {hh}:{ii}:{ss}": "{dd}/{mm}/{yy} {hh}:{ii}:{ss}"
    "{dd}/{mm}/{yy}": "{dd}/{mm}/{yy}"
    "{mm}.{dd}.{yy} {hh}:{ii}:{ss} {tz}": "{mm}.{dd}.{yy} {hh}:{ii}:{ss} {tz}"
    "{mm}.{dd}.{yy} {hh}:{ii}:{ss}": "{mm}.{dd}.{yy} {hh}:{ii}:{ss}"
    "{mm}.{dd}.{yy}": "{mm}.{dd}.{yy}"
    "{mm}-{dd}-{yy} {hh}:{ii}:{ss} {tz}": "{mm}-{dd}-{yy} {hh}:{ii}:{ss} {tz}"
    "{mm}-{dd}-{yy} {hh}:{ii}:{ss}": "{mm}-{dd}-{yy} {hh}:{ii}:{ss}"
    "{mm}-{dd}-{yy}": "{mm}-{dd}-{yy}"
    "{mm}/{dd}/{yy} {hh}:{ii}:{ss} {tz}": "{mm}/{dd}/{yy} {hh}:{ii}:{ss} {tz}"
    "{mm}/{dd}/{yy} {hh}:{ii}:{ss}": "{mm}/{dd}/{yy} {hh}:{ii}:{ss}"
    "{mm}/{dd}/{yy}": "{mm}/{dd}/{yy}"
    "{yyyy}年{m}月{d}日 {hh}時{ii}分{ss}秒": "{yyyy}年{m}月{d}日 {hh}時{ii}分{ss}秒"
    "{yyyy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}": "{yyyy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}"
    "{yyyy}年{m}月{d}日": "{yyyy}年{m}月{d}日"
    "{yy}年{m}月{d}日 {hh}時{ii}分{ss}秒": "{yy}年{m}月{d}日 {hh}時{ii}分{ss}秒"
    "{yy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}": "{yy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}"
    "{yy}年{m}月{d}日": "{yy}年{m}月{d}日"
    "{yyyy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초": "{yyyy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초"
    "{yyyy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}": "{yyyy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}"
    "{yyyy}년 {m}월 {d}일": "{yyyy}년 {m}월 {d}일"
    "{yy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초": "{yy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초"
    "{yy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}": "{yy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}"
    "{yy}년 {m}월 {d}일": "{yy}년 {m}월 {d}일"
    "{yyyy}-{mm}-{dd}T{hh}:{ii}:{ss}{t:z}": "{yyyy}-{mm}-{dd}T{hh}:{ii}:{ss}{t:z}"
    "{d}. {m}. {yyyy}": "{d}. {m}. {yyyy}"
  ipaddr:
   type: string
   default: "REMOTE_ADDR"
  enable_plugins:
   type: bool
   default: true
  forbid_on_block:
   type: bool
   default: true
  delete_on_sight:
   type: bool
   default: false
  lang:
   type: string
   default: "en"
   choices:
    en: English
    ar: العربية
    bn: বাংলা
    de: Deutsch
    es: Español
    fr: Français
    hi: हिंदी
    id: Bahasa Indonesia
    it: Italiano
    ja: 日本語
    ko: 한국어
    nl: Nederlandse
    no: Norsk
    pl: Polski
    pt: Português
    ru: Русский
    sv: Svenska
    th: ภาษาไทย
    tr: Türkçe
    ur: ‏اردو‏
    vi: Tiếng Việt
    zh: 中文（简体）
    zh-tw: 中文（傳統）
   choice_filter: "FilterLang"
  numbers:
   type: string
   default: "Latin-1"
   choices:
    NoSep-1: "1234567.89"
    NoSep-2: "1234567,89"
    Latin-1: "1,234,567.89"
    Latin-2: "1 234 567.89"
    Latin-3: "1.234.567,89"
    Latin-4: "1 234 567,89"
    Latin-5: "1,234,567·89"
    China-1: "123,4567.89"
    India-1: "12,34,567.89"
    India-2: "१२,३४,५६७.८९"
    Bengali-1: "১২,৩৪,৫৬৭.৮৯"
    Arabic-1: "١٢٣٤٥٦٧٫٨٩"
    Arabic-2: "١٬٢٣٤٬٥٦٧٫٨٩"
    Thai-1: "๑,๒๓๔,๕๖๗.๘๙"
  quarantine_key:
   type: string
   default: ""
  quarantine_max_filesize:
   type: kb
   step: any
   default: "2MB"
   preview: kb
  quarantine_max_usage:
   type: kb
   step: any
   default: "64MB"
   preview: kb
  honeypot_mode:
   type: bool
   default: false
  scan_cache_expiry:
   type: int
   default: 21600
   preview: seconds
  disable_cli:
   type: bool
   default: false
  disable_frontend:
   type: bool
   default: true
  max_login_attempts:
   type: int
   default: 5
  FrontEndLog:
   type: string
   default: ""
  disable_webfonts:
   type: bool
   default: false
  maintenance_mode:
   type: bool
   default: false
  default_algo:
   type: string
   default: "PASSWORD_DEFAULT"
   choices:
    PASSWORD_DEFAULT: PASSWORD_DEFAULT
    PASSWORD_BCRYPT: PASSWORD_BCRYPT
    PASSWORD_ARGON2I: PASSWORD_ARGON2I (PHP >= 7.2.0)
   choice_filter: "FilterAlgo"
  statistics:
   type: bool
   default: false
 signatures:
  Active:
   type: string
   default: ""
  fail_silently:
   type: bool
   default: true
  fail_extensions_silently:
   type: bool
   default: true
  detect_adware:
   type: bool
   default: true
  detect_joke_hoax:
   type: bool
   default: true
  detect_pua_pup:
   type: bool
   default: true
  detect_packer_packed:
   type: bool
   default: true
  detect_shell:
   type: bool
   default: true
  detect_deface:
   type: bool
   default: true
  detect_encryption:
   type: bool
   default: true
 files:
  max_uploads:
   type: int
   default: 10
  filesize_limit:
   type: kb
   step: any
   default: "64MB"
   preview: kb
  filesize_response:
   type: bool
   default: true
  filetype_whitelist:
   type: string
   default: ""
  filetype_blacklist:
   type: string
   default: "386,acc*,acm,act*,apk,app,ash*,asm*,asx*,ax,bat,bin,ccc,cgi,cmd,com*,cpl,cpp,csh,dll,drv,elf,exe,fxp,gad*,hta*,htp*,ico,inf,ins,inx,ipa,isu,job,js,jse,ksh,lnk,msc,msi,msp,mst,net,ocx,ops,org,osx,out,paf,php*,pif,pl,prg,ps1,reg,rgs,rs,run,scr*,sct,shb,shs,sql*,sys,u3p,url,vb,vbe,vbs*,wor*,ws,wsf,xsl"
  filetype_greylist:
   type: string
   default: ""
  check_archives:
   type: bool
   default: true
  filesize_archives:
   type: bool
   default: true
  filetype_archives:
   type: bool
   default: false
  max_recursion:
   type: int
   default: 10
  block_encrypted_archives:
   type: bool
   default: true
 attack_specific:
  chameleon_from_php:
   type: bool
   default: true
  chameleon_from_exe:
   type: bool
   default: true
  chameleon_to_archive:
   type: bool
   default: true
  chameleon_to_doc:
   type: bool
   default: true
  chameleon_to_img:
   type: bool
   default: true
  chameleon_to_pdf:
   type: bool
   default: true
  archive_file_extensions:
   type: string
   default: "7z,a,ace,alz,apk,app,ar,arc,arj,ba,bh,bz,bz2,dmg,gz,ice,iso,lha,lz,lzh,lzo,lzw,lzx,mar,pak,pck,pea,phar,rar,rz,s7z,sea,sen,sfx,shar,sqx,tar,tgz,tlz,xar,xp3,xz,yz1,z,zz,paq*,sit*,tbz*,zip*"
  block_control_characters:
   type: bool
   default: false
  corrupted_exe:
   type: bool
   default: true
  decode_threshold:
   type: kb
   step: any
   default: "512KB"
   preview: kb
  scannable_threshold:
   type: kb
   step: any
   default: "32MB"
   preview: kb
 compatibility:
  ignore_upload_errors:
   type: bool
   default: false
  only_allow_images:
   type: bool
   default: false
 heuristic:
  threshold:
   type: int
   default: 3
 virustotal:
  vt_public_api_key:
   type: string
   default: ""
  vt_suspicion_level:
   type: int
   default: 1
  vt_weighting:
   type: int
   default: 0
  vt_quota_rate:
   type: int
   default: 4
  vt_quota_time:
   type: int
   default: 1
   preview: minutes
 urlscanner:
  lookup_hphosts:
   type: bool
   default: true
  google_api_key:
   type: string
   default: ""
  maximum_api_lookups:
   type: int
   default: 10
  maximum_api_lookups_response:
   type: bool
   default: false
  cache_time:
   type: int
   default: 3600
   preview: seconds
 template_data:
  theme:
   type: string
   default: "default"
   choices:
    default: "Default"
    rbi: "Red-Blue Inverted"
    slate: "Slate"
    bluemetal: "Blue Metal"
    moss: "Moss"
    fullmoon: "Full Moon"
    unicorn: "Unicorn"
   choice_filter: "FilterTheme"
  Magnification:
   type: real
   step: any
   default: 1
  css_url:
   type: string
   default: ""

